spring.application.name=helpdesk-backend

# database
spring.datasource.url=jdbc:postgresql://localhost:5432/helpdesk_db
spring.datasource.username=postgres
spring.datasource.password=root

# hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# chat memory
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

# gemini setup
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

# Email config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=email.com
spring.mail.password=password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
