services:
  postgres:
    image: postgres:16
    container_name: helpdesk_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./helpdesk-backend
    container_name: helpdesk-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./helpdesk-frontend
    container_name: helpdesk-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend



volumes:
  postgres_data:
